name: Go Vulnerability Checker
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: goversion
        run: echo "goversion=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.goversion.outputs.goversion }}
      - run: date
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest && govulncheck ./...
